package com.example.testretrofitapp.presentation.weekForecast.weekForecastRecyclerView

import androidx.recyclerview.widget.RecyclerView
import com.example.testretrofitapp.databinding.WeekWeatherItemBinding
import com.example.testretrofitapp.databinding.WeekWeatherItemSecondBinding

class WeatherViewHolder (val binding: WeekWeatherItemSecondBinding):RecyclerView.ViewHolder(binding.root)
//заменили с WeekWeatherItemBinding на WeekWeatherItemSecondBinding